### PR TITLE
Add a ratio to "res/config.json"

### PR DESCRIPTION
**Pull request by tleger1958**
Hello,

I had to add the ratio of my screen resolution so that the program could run correctly.

I therefore propose to add it, as evanbowman suggested to me.

### CODE REVIEW

**Comment by evanbowman** [comment]
Hi, thanks for creating a pull request! 

Before I merge the pull request, would you be able to make one change?

If you look at the other resolutions in the config.json file, they intentionally use small resolutions.

For example, a 1920x1086 resolution has a 16:9 aspect ratio, and will render to a 832x468 region. The game renders to a small resolution on purpose, it is part of the game's visual design.

Would you be able to replace the 1366x768 width and height with smaller values that are more similar to the areas of the other entries? For example:

832 * 468 = 389376
784 * 490 = 384160
695 * 556 = 386420

Can you pick values that are a 683:384 aspect ratio, but multiply to a similar area as the other options?

Does that make sense? I can explain more if it would help

**Comment by evanbowman** [comment]
The reason for the similar areas is to give the game a consistent appearance across different displays

**Comment by tleger1958** [comment]
No, I can’t.
My resolution is 1366x768 = 683x384, and gcd(683,364)=1.
So, I can’t give a smaller fraction.
It is a very strange resolution...

**Comment by evanbowman** [comment]
Oh I understand, thank you

**Pull request merged**
